#!/usr/bin/env bash
echo $1
echo $2
if [ $# -ne 2 ] 
then
    exit 0 #Only received one parameter
fi
head=`git rev-parse --verify HEAD`
git checkout $1 2>>/dev/null
files=`git diff --name-only $2`
cd `git rev-parse --show-toplevel`
before=`./cpplint.py $files 2>&1 |awk '/Total errors found/ {print $4}'` 
git checkout $2 2>/dev/null
after=`./cpplint.py $files 2>&1 |awk '/Total errors found/ {print $4}'`
git checkout $head 2>/dev/null
cd - 
if [ $after -gt $before ] 
then
echo You have introduced checkstyle errors.
#$(( $after - $before )) checkstyle errors.
   exit 1
else
   exit 0
fi
